# Generated by Django 4.2.5 on 2023-11-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'managed': True},
        ),
    ]
