# Generated by Django 4.2.5 on 2023-11-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0002_alter_part_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='branchesparts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workorderstatus',
            options={'managed': True},
        ),
    ]
