# Generated by Django 4.2.5 on 2023-11-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0003_alter_branch_options_alter_branchesparts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchesparts',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.branch'),
        ),
        migrations.AddField(
            model_name='branchesparts',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.part'),
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_quotes', to='car_dealership.user'),
        ),
        migrations.AddField(
            model_name='quote',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller_quotes', to='car_dealership.user'),
        ),
        migrations.AddField(
            model_name='quote',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.vehicle'),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller_sales', to='car_dealership.user'),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.vehicle'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.role'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.branch'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_work_orders', to='car_dealership.user'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.workorderstatus'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.vehicle'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='workshop_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_manager_work_orders', to='car_dealership.user'),
        ),
    ]
