name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build
        run: |
          python manage.py collectstatic --noinput
          python manage.py migrate
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/car_dealership_backend
            sudo apt update
            sudo apt install python3-pip
            sudo pip3 install -r requirements.txt
            sudo python3 manage.py collectstatic --noinput
            sudo python3 manage.py migrate
            sudo systemctl restart car_dealership_backend
